services:
  mysql_206:
    env_file:
     - .env
    container_name:  mysql_206
    image: mysql:8
    restart: always
   
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: